# serverless.yml

service: coins-ohlc-guardar-datos-gs
useDotenv: true

provider:
  name: aws
  runtime: nodejs16.x
  region: us-east-2
  stage: prod
  environment:
      DB_HOST: ${env:DB_HOST}
      DB_USER: ${env:DB_USER}
      DB_PASSWORD: ${env:DB_PASSWORD}
      DB_PORT: ${env:DB_PORT}
      DB_DATABASE: ${env:DB_DATABASE}

functions:
  guardarOHLC30minutosGS:
    handler: guardarOHLC30min.handler
    memorySize: 256
    name: guardarOHLC30minutosGS
    description: LCF9 - Función que obtiene el OHLC de la base de datos y lo guarda en Google SpreadSheet.
    timeout: 180
    maximumRetryAttempts: 0
    environment:
      TABLE_OHLC: ${env:TABLE_OHLC_MIN}
      ID_HOJA_RANGO: ${env:ID_HOJA_RANGO1}
      SPREADSHEET_ID_CP1: ${env:SPREADSHEET_ID_CP1_MIN}
      SPREADSHEET_ID_CP2: ${env:SPREADSHEET_ID_CP2_MIN}
    events:
      - eventBridge:
          schedule: cron(15 11,13,15,17,19,21,23,01,03 ? * * *)
  guardarOHLC4horasGS:
    handler: index.handler
    memorySize: 256
    name: guardarOHLC4horasGS
    description: LCF10 - Función que obtiene el OHLC de la base de datos y lo guarda en Google SpreadSheet.
    timeout: 180
    maximumRetryAttempts: 0
    environment:
      TABLE_OHLC: ${env:TABLE_OHLC_HORA}
      ID_HOJA_RANGO: ${env:ID_HOJA_RANGO2}
      SPREADSHEET_ID_CP1: ${env:SPREADSHEET_ID_CP1}
      SPREADSHEET_ID_CP2: ${env:SPREADSHEET_ID_CP2}
      SPREADSHEET_ID_CP3: ${env:SPREADSHEET_ID_CP3}
    events:
      - eventBridge:
          schedule: cron(20 8 ? * * *)
  guardarOHLC4diasGS:
    handler: index.handler
    memorySize: 256
    name: guardarOHLC4diasGS
    description: LCF11 - Función que obtiene el OHLC de la base de datos y lo guarda en Google SpreadSheet.
    timeout: 180
    maximumRetryAttempts: 0
    environment:
      TABLE_OHLC: ${env:TABLE_OHLC_DIA}
      ID_HOJA_RANGO: ${env:ID_HOJA_RANGO3}
      SPREADSHEET_ID_CP1: ${env:SPREADSHEET_ID_CP1}
      SPREADSHEET_ID_CP2: ${env:SPREADSHEET_ID_CP2}
      SPREADSHEET_ID_CP3: ${env:SPREADSHEET_ID_CP3}
    events:
      - eventBridge:
          schedule: cron(20 8 ? * * *)